const Router = require('express')
const router = new Router()
const userRouter = require('./userRouter')
const categoryRouter = require('./categoryRouter')
const ingridientRouter = require('./ingridientRouter')
const nationalityRouter = require('./nationalityRouter')
const productRouter = require('./productRouter')
const specialGroupRouter = require('./specialGroupRouter')
const dishRouter = require('./dishRouter')
const measureRouter = require('./measureRouter')
const messagesRouter = require('./messagesRouter')
const compoundRouter = require('./compoundRouter')

router.use('/user', userRouter)
router.use('/category', categoryRouter)
router.use('/dish', dishRouter)
router.use('/ingridient', ingridientRouter)
router.use('/nationality', nationalityRouter)
router.use('/product', productRouter)
router.use('/specialgroup', specialGroupRouter)
router.use('/measure', measureRouter)
router.use('/messages', messagesRouter)
router.use('/compound', compoundRouter)

module.exports = router